class AuthenticationError(Exception):
    pass

class NotFoundError(Exception):
    pass

